const test = {
  id: 'cs_test_b17dlXpn1Q3Nn8tYWicoo0uJeAvmgZjivE7GlLisXCIY6egM4Lh2n9exyt',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: true,
  amount_subtotal: 22500,
  amount_total: 24997,
  automatic_tax: { enabled: false, status: null },
  billing_address_collection: 'required',
  cancel_url: 'http://127.0.0.1:3000/cart',
  client_reference_id: 'REF_ID_211381203',
  consent: null,
  consent_collection: null,
  created: 1666497048,
  currency: 'usd',
  customer: 'cus_Mep4rfxWNVymF5',
  customer_creation: null,
  customer_details: {
    address: {
      city: 'Brooklyn',
      country: 'US',
      line1: '530 east 99th street',
      line2: '',
      postal_code: '11236',
      state: 'NY',
    },
    email: 'lumpkinstudios@gmail.com',
    name: 'Keanu Studios',
    phone: '+16469569099',
    tax_exempt: 'none',
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1666583448,
  livemode: false,
  locale: null,
  metadata: {
    user_DB: 'lstudios2431',
    order_number: 'NRE001-857470690',
    all_items:
      '[{"qty":5,"total":75,"ProductID":"WSH-14631376","color":"black","size":"m","images":["noire-kind-1-black.jpg"],"name":"Noire Kind","price":15,"category":"PANTIES","subCategory":"SHORTS"},{"qty":2,"total":150,"ProductID":"BDST-56423211","color":"pink","size":"m","images":["fancy-contrast-pink-1.webp","fancy-contrast-pink-2.webp"],"name":"Fancy Contrast","price":75,"category":"LINGERIE","subCategory":"BODYSUIT"}]',
  },
  mode: 'payment',
  payment_intent: 'pi_3LvvDPDDM79MM6Ap1oEDS616',
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_options: {},
  payment_method_types: ['card', 'us_bank_account'],
  payment_status: 'paid',
  phone_number_collection: { enabled: true },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: { allowed_countries: ['US', 'CA', 'MX', 'GB'] },
  shipping_cost: {
    amount_subtotal: 500,
    amount_tax: 0,
    amount_total: 500,
    shipping_rate: 'shr_1LvvD2DDM79MM6ApprFjZBgC',
  },
  shipping_details: {
    address: {
      city: 'Brooklyn',
      country: 'US',
      line1: '530 east 99th street',
      line2: null,
      postal_code: '11236',
      state: 'NY',
    },
    name: 'Keanu Studios',
  },
  shipping_options: [
    {
      shipping_amount: 500,
      shipping_rate: 'shr_1LvvD2DDM79MM6ApprFjZBgC',
    },
    {
      shipping_amount: 1000,
      shipping_rate: 'shr_1LvvD2DDM79MM6Ap7OC09PHS',
    },
  ],
  status: 'complete',
  submit_type: null,
  subscription: null,
  success_url: 'http://127.0.0.1:3000/account/orders',
  total_details: { amount_discount: 0, amount_shipping: 500, amount_tax: 1997 },
  url: null,
};
