const test = {
  status: 'processing',
  order_date: {
    date_keys: { date: 23, month: 9, year: 2022 },
    date_ms: 1666517405,
  },
  order_number: 'NRE001-773135953',
  order_user: 'lstudios2431',
  stripe_order_id:
    'cs_test_b1utJGLq3r70vCD6JwzxCwUiM9z3AxTb47nfTwLr3bxBm0mVhlJi86anQ9',
  subTotal: 22500,
  allTotal: 24997,
  client_reference_id: 'REF_ID_989026704',
  stripe_customer_id: 'cus_Mep4rfxWNVymF5',
  customerInfo: {
    username: 'lstudios2431',
    name: 'Keanu Studios',
    emailAddress: 'lumpkinstudios@gmail.com',
    phoneNumber: '+16469569099',
  },
  shipping_info: {
    shipping_choice: {
      name: 'standard',
      speed: [Array],
      cost: 5,
      ship_ref_stripe: 'shr_1LvXbmDDM79MM6ApDi6UAETu',
    },
    address: {
      city: 'Brooklyn',
      country: 'US',
      line1: '530 east 99th street',
      line2: null,
      postal_code: '11236',
      state: 'NY',
      name: 'Keanu Studios',
    },
  },
  product_info: [
    {
      qty: 5,
      total: 75,
      ProductID: 'WSH-14631376',
      color: 'black',
      size: 'm',
      images: [Array],
      name: 'Noire Kind',
      price: 15,
      category: 'PANTIES',
      subCategory: 'SHORTS',
    },
    {
      qty: 2,
      total: 150,
      ProductID: 'BDST-56423211',
      color: 'pink',
      size: 'm',
      images: [Array],
      name: 'Fancy Contrast',
      price: 75,
      category: 'LINGERIE',
      subCategory: 'BODYSUIT',
    },
  ],
};
